###
POST http://127.0.0.1:6688/api/signup
Content-Type: application/json

{
  "workspace": "acme",
  "fullname": "zhangliqun",
  "email": "qazwsx2228@163.com",
  "password":"123456"
}
###
POST http://127.0.0.1:6688/api/signup
Content-Type: application/json

{
  "workspace": "acme",
  "fullname": "zhangli",
  "email": "908388349@qq.com",
  "password":"123456"
}
###
POST http://127.0.0.1:6688/api/signin
Content-Type: application/json

{
  "email": "qazwsx2228@163.com",
  "password":"123456"
}
> {% client.global.set("auth_token", response.body.token); %}
###
GET http://127.0.0.1:6688/api/users
authorization: Bearer {{auth_token}}

###


POST http://127.0.0.1:6688/api/chats
Content-Type: application/json
authorization: Bearer {{auth_token}}

{
  "name": "acme",
  "members": [1, 2],
  "public": false
}

###
GET http://127.0.0.1:6688/api/chats
authorization: Bearer {{auth_token}}

###
GET http://127.0.0.1:6688/api/chats/2
authorization: Bearer {{auth_token}}

###
PATCH http://127.0.0.1:6688/api/chats/2
Content-Type: application/json
authorization: Bearer {{auth_token}}

{
  "name": "acme1",
  "members": [1, 2],
  "public": true
}

###
DELETE http://127.0.0.1:6688/api/chats/2
authorization: Bearer {{auth_token}}