###
POST http://127.0.0.1:6688/api/signup
Content-Type: application/json

{
  "workspace": "acme",
  "fullname": "zhangliqun",
  "email": "qazwsx22289@163.com",
  "password":"123456"
}
###
POST http://127.0.0.1:6688/api/signup
Content-Type: application/json

{
  "workspace": "acme",
  "fullname": "zhangli",
  "email": "908388349@qq.com",
  "password":"123456"
}

###
POST http://127.0.0.1:6688/api/signin
Content-Type: application/json

{
  "email": "tchen2@acme.org",
  "password":"123456"
}
###
POST http://127.0.0.1:6688/api/signin
Content-Type: application/json

{
  "email": "tchen1@acme.org",
  "password":"123456"
}
> {% client.global.set("auth_token", response.body.token); %}
###
GET http://127.0.0.1:6688/api/users
authorization: Bearer {{auth_token}}

###


POST http://127.0.0.1:6688/api/chats
Content-Type: application/json
authorization: Bearer {{auth_token}}

{
  "name": "acme",
  "members": [1, 2],
  "public": false
}

###
GET http://127.0.0.1:6688/api/chats
authorization: Bearer {{auth_token}}

###
GET http://127.0.0.1:6688/api/chats/2
authorization: Bearer {{auth_token}}

###
PATCH http://127.0.0.1:6688/api/chats/2
Content-Type: application/json
authorization: Bearer {{auth_token}}

{
  "name": "acme测试",
  "members": [1, 2],
  "public": false
}

###
DELETE http://127.0.0.1:6688/api/chats/2
authorization: Bearer {{auth_token}}


### upload  file
POST http://127.0.0.1:6688/api/upload
authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; filename="details.png"
Content-Type: application/octet-stream

< C:\Users\hearsay316\Pictures\details.png
--MyBoundary
Content-Disposition: form-data; filename="hello.txt"
Content-Type: text/plain

Hello, World!
--MyBoundary--
### upload  file
GET  http://127.0.0.1:6688/api/files/1/7fb/758/dc52840e6bd4c4d15c2d89d6c83aaf12b0.png
authorization: Bearer {{auth_token}}


###
POST  http://127.0.0.1:6688/api/chats/1
authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "content": "hello word1111",
  "files": []
}

###
GET  http://127.0.0.1:6688/api/chats/1/messages?limit=6
authorization: Bearer {{auth_token}}

###
POST  https://ffzzhdyy-xrfqdxra-8okrqcuzclty.vcc3.mcprev.cn/users
Content-Type: application/json

{
  "username": "liucheng"
}